services:
  django:
    build:
      context: ./LibShai-Backend
      dockerfile: "Dockerfile"
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./LibShai-Backend:/app
  vue:
    build:
      context: ./LibShai-Frontend
      dockerfile: "Dockerfile"
    command: "npm run dev"
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./LibShai-Frontend:/app
