services:

  django:
    build:
      context: ./LibShai-Backend
      dockerfile: "Dockerfile"
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./LibShai-Backend:/app
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_STORAGE_BUCKET_NAME: ${AWS_STORAGE_BUCKET_NAME}
      USE_AWS_S3: ${USE_AWS_S3}
      DEBUG: ${DEBUG}

  vue:
    build:
      context: ./LibShai-Frontend
      dockerfile: "Dockerfile"
    command: "npm run dev"
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./LibShai-Frontend:/app
